pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        git branch: 'main', url: 'https://github.com/Gadilasruthilaya/learn_jenkins.git'
        sh 'cd javacode'
        sh 'javac hello_world.java'
        sh 'mvn --version'
        sh 'hello world java program executed'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        git branch: 'main', url: 'https://github.com/Gadilasruthilaya/learn_jenkins.git'
        sh 'cd javacode'
        sh 'node app.js'
        sh 'node --version'
        sh 'node program executed successfully'
      }
    }
  }
}
